# Generated by Django 3.0.5 on 2020-05-11 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='board title')),
                ('description', models.CharField(max_length=200, verbose_name='board description')),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='foil title')),
                ('description', models.CharField(max_length=200, verbose_name='foil description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Board')),
            ],
            options={
                'db_table': 'builds',
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='controller title')),
                ('description', models.CharField(max_length=200, verbose_name='controller description')),
            ],
            options={
                'db_table': 'controllers',
            },
        ),
        migrations.CreateModel(
            name='Foil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='foil title')),
                ('description', models.CharField(max_length=200, verbose_name='foil description')),
            ],
            options={
                'db_table': 'foils',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='motor title')),
                ('description', models.CharField(max_length=200, verbose_name='motor description')),
            ],
            options={
                'db_table': 'motors',
            },
        ),
        migrations.CreateModel(
            name='Propellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='propellor title')),
                ('description', models.CharField(max_length=200, verbose_name='propellor description')),
            ],
            options={
                'db_table': 'propellors',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ride title')),
                ('description', models.CharField(max_length=200, verbose_name='ride description')),
                ('ride_date', models.DateField(verbose_name='date of ride')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='date uploaded')),
                ('build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride', to='plotter.Build')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Controller'),
        ),
        migrations.AddField(
            model_name='build',
            name='foil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Foil'),
        ),
        migrations.AddField(
            model_name='build',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Motor'),
        ),
        migrations.AddField(
            model_name='build',
            name='propellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Propellor'),
        ),
    ]
