# Generated by Django 3.0.5 on 2020-05-11 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plotter', '0002_auto_20200510_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL),
        ),
    ]
