# Generated by Django 3.0.5 on 2020-05-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_auto_20200510_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='location'),
        ),
        migrations.CreateModel(
            name='CsvRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_time', models.IntegerField()),
                ('temp_motor', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('current_motor', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('current_in', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('d_axis_current', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('q_axis_current', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('erpm', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('duty_cycle', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('amp_hours_used', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('amp_hours_charged', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('watt_hours_used', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('watt_hours_charged', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='plotter.Ride')),
            ],
        ),
    ]
