# Generated by Django 3.0.5 on 2020-05-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0005_auto_20200511_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='board description'),
        ),
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='foil description'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='controller description'),
        ),
        migrations.AlterField(
            model_name='foil',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='foil description'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='motor description'),
        ),
        migrations.AlterField(
            model_name='propeller',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='propeller description'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='ride description'),
        ),
    ]
