# Generated by Django 3.0.5 on 2020-05-13 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plotter', '0006_auto_20200512_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvrow',
            name='ride',
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='file name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='plotter.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='csvrow',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='row', to='plotter.CsvFile'),
            preserve_default=False,
        ),
    ]
