# Generated by Django 3.0.5 on 2020-05-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0007_auto_20200512_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvrow',
            name='file',
        ),
        migrations.AddField(
            model_name='csvrow',
            name='ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='row', to='plotter.Ride'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='file name'),
        ),
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
