# Generated by Django 3.0.5 on 2020-05-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0008_auto_20200512_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
