# Generated by Django 3.0.5 on 2020-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0009_ride_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='build description'),
        ),
        migrations.AlterField(
            model_name='build',
            name='title',
            field=models.CharField(max_length=50, verbose_name='build title'),
        ),
    ]
