# Generated by Django 3.0.5 on 2020-05-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0011_build_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvrow',
            old_name='ms_time',
            new_name='ms_today',
        ),
    ]
