# Generated by Django 3.0.5 on 2020-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0013_auto_20200518_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrow',
            name='ms_today',
            field=models.IntegerField(),
        ),
    ]
