# Generated by Django 3.0.5 on 2020-05-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0014_auto_20200519_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvrow',
            old_name='amp_hours_charged',
            new_name='input_voltage',
        ),
        migrations.RenameField(
            model_name='csvrow',
            old_name='d_axis_current',
            new_name='tachometer',
        ),
        migrations.RenameField(
            model_name='csvrow',
            old_name='q_axis_current',
            new_name='temp_mos_max',
        ),
        migrations.RemoveField(
            model_name='csvrow',
            name='temp_motor',
        ),
        migrations.RemoveField(
            model_name='csvrow',
            name='watt_hours_charged',
        ),
    ]
