# Generated by Django 3.0.5 on 2020-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0015_auto_20200519_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrow',
            name='amp_hours_used',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='current_in',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='current_motor',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='duty_cycle',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='erpm',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='input_voltage',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='tachometer',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='temp_mos_max',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='csvrow',
            name='watt_hours_used',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
    ]
