# Generated by Django 3.0.5 on 2020-05-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0016_auto_20200519_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvrow',
            name='tachometer',
        ),
    ]
