# Generated by Django 3.0.5 on 2020-05-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0017_remove_csvrow_tachometer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='battery title')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='battery description')),
            ],
            options={
                'db_table': 'batteries',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Battery'),
        ),
    ]
