# Generated by Django 3.0.5 on 2020-05-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0018_auto_20200521_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='battery',
        ),
    ]
