# Generated by Django 3.0.5 on 2020-05-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0019_remove_build_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Battery'),
        ),
    ]
