# Generated by Django 3.0.5 on 2020-05-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0020_build_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='remote title')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='remote description')),
            ],
            options={
                'db_table': 'remotes',
            },
        ),
        migrations.AlterField(
            model_name='build',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Remote'),
        ),
    ]
