# Generated by Django 3.0.5 on 2020-05-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0021_auto_20200521_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Remote'),
        ),
        migrations.AlterField(
            model_name='build',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build', to='plotter.Battery'),
        ),
    ]
